### PR TITLE
Pager

### PR DESCRIPTION
**Pull request by Eugen-save**

### CODE REVIEW

**Comment by Krzysztof-Jaczewski** [comment]
@Eugen-save  Nice Work,  😉
Have few little thing to fix:
- margins don`t colappging in display:flex, so space between element is too high, atleast higher then in project
( * you can use gap, works in flex too😉 )

- you can aslo pull main brach, there is folder images and add there jour svg images and change imports paths 😉

- I think you should make styling on mobiles too, and numbers as props, and some condition, because there are no names in buttons on mobiles 😉

- padding in buttons is 31px =, in project is 16px 

- props for buttons are unnessesary i think when you fix flex

fix this and marge feel fre to merge it 😎

**Comment by Krzysztof-Jaczewski** [comment]
you can aslo pull main brach, there is folder images and add there jour svg images and change imports paths 😉

**Comment by Krzysztof-Jaczewski** [comment]
I think you should make styling on mobiles too, and make names of buttons and numbers as props, and some condition, because there are no names in buttons on mobiles

**Comment by Eugen-save** [comment]
@Krzysztof-Jaczewski thank you for your notices, i've fixed margin problem and I hope merge problem is also fixed. But I need some time to make mobile look for buttons (delete texts and add additional svg images). Do I need to make a function or I can also make it in CSS, please help if you can :)

**Comment by Krzysztof-Jaczewski** [comment]
Hey @Eugen-save 🙂 take your time, you need to make condiction and compare window.innerwidth to our breakpoint in our theme, with ternary operator I think, but as you like😉 try yourself and write if you will need help😉

**Comment by Eugen-save** [comment]
@Krzysztof-Jaczewski I've edited mobile look of buttons, now they look like as in project :)

**Comment by Krzysztof-Jaczewski** [comment]
Cool😀 @Eugen-save  so merge your branch to main, if we notice some glitches we will fix them when we will be adding logic to Pager🙂 Nicely done😉

**Pull request merged**
